/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_convo;

import java.text.MessageFormat;
import java.awt.print.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.*;
/**
 *
 * @author joseph chek
 */
public class Convo extends javax.swing.JFrame {
DefaultTableModel model=new DefaultTableModel();
    String d;
/**
     * Creates new form Convo
     */
    public Convo() {
        initComponents();
         model.addColumn("Nom");
        model.addColumn("DATE_JOUR");
        model.addColumn("Horaire");
         model.addColumn("Nom_sal");
        model.addColumn("Nom_mat");
        model.addColumn("duree");
       
        
         try{
//2.Enregistrer le driver JDBC
Class.forName("com.mysql.jdbc.Driver");
}catch(ClassNotFoundException e)
{System.out.println("erreur du chargement du driver"+e);
}
        try{
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
//4creation d'un Statement

Statement st=con.createStatement();

//5.execution d'une requete (ResultSet)

ResultSet Rs=st.executeQuery("select Nom,DATE_JOUR,Horaire,Nom_sal,lib_mat,Duree from enseignant,matiére,salle,affecter"
                    + " WHERE enseignant.Id = affecter.Id "
                    + "and salle.Id_sal = affecter.Id_sal  "
                    + "and matiére.Id_mat = affecter.Id_mat "
                    + "and  Nom = '"+t7.getText()+"'");
            while(Rs.next()){
                model.addRow(new Object[]{Rs.getString("Nom"),Rs.getString("DATE_JOUR"),Rs.getString("Horaire"),Rs.getString("Nom_sal"),Rs.getString("lib_mat"),Rs.getString("duree")});
            }



st.close();
con.close();
}

catch (SQLException sql){
System.err.println("erreur lors de la connexion"+sql);
 
}
        tbl.setModel(model);
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        BT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(t7);
        t7.setBounds(420, 180, 190, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/recher.png"))); // NOI18N
        jButton1.setText("Rechercher l' enseignant ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 175, 270, 45);

        BT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/imprim.png"))); // NOI18N
        BT.setText("IMPRIMER");
        BT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTActionPerformed(evt);
            }
        });
        getContentPane().add(BT);
        BT.setBounds(350, 340, 200, 57);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "date_jour", "Horaire", "Salle", "Matiére", "Durée"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 240, 570, 90);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gestion de Convocation des Examens");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 10, 710, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/uu.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 0, 110, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/cooooo.png"))); // NOI18N
        jLabel1.setText("Convocation");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 90, 360, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/F.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 910, 50);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/retour.png"))); // NOI18N
        jButton5.setText("Retour");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 70, 160, 40);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/decon.png"))); // NOI18N
        jButton2.setText("Deconnexion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(680, 70, 220, 50);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Copyright MI3-Info juin 2015");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(310, 480, 400, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/F.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 480, 910, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/VRAI.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 60, 910, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTActionPerformed
        // TODO add your handling code here:
        
        

        MessageFormat header= new MessageFormat("CONVOCATION de l'Enseignant");
        
        
        MessageFormat  footer= new MessageFormat("page(0,number,integer)");
        try{
            tbl.print(JTable.PrintMode.NORMAL, header,footer);}
        catch(java.awt.print.PrinterException e){
            System.err.format("cannot print %s%n", e.getMessage());
        }

    }//GEN-LAST:event_BTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            //2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException e)
        {System.out.println("erreur du chargement du driver"+e);
        }
        try{
            //3.connextion a la basse

            //String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
            //4creation d'un Statement

            Statement st=con.createStatement();

            model.setRowCount(0);//pour vider la liste des client

            ResultSet Rs=st.executeQuery("select Nom,DATE_JOUR,Horaire,Nom_sal,lib_mat,Duree from enseignant,matiére,salle,affecter"
                    + " WHERE enseignant.Id = affecter.Id "
                    + "and salle.Id_sal = affecter.Id_sal  "
                    + "and matiére.Id_mat = affecter.Id_mat "
                    + "and  Nom = '"+t7.getText()+"'");

            while (Rs.next()){
                Object[] enseignant={Rs.getString(1),Rs.getString(2),Rs.getString(3),Rs.getString(4),Rs.getString(5),Rs.getString(6)};
                model.addRow(enseignant);
               
            } if (model.getRowCount()== 0){JOptionPane.showMessageDialog(null,"Ce enseignant n' est pas encore affecter !!");

            } 
               
            
        }catch (Exception e){ System.err.println(e);
            JOptionPane.showMessageDialog(null,"erreur\n"+e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
 
        
         try{
            int i=tbl.getSelectedRow();
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());}
    }//GEN-LAST:event_tblMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        affecter AP =new affecter();
                AP.setSize(927, 556);
                AP.setVisible(true);
                 this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Administrateur A =new Administrateur();
                A.setSize(927, 556);
                A.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  Convo A =new Convo();
                A.setSize(927, 556);
                A.setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t7;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
