/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_convo;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joseph chek
 */
public class ENSEIGNANTS extends javax.swing.JFrame {
DefaultTableModel model=new DefaultTableModel();
    /**
     * Creates new form ENSEIGNANTS
     */
    public ENSEIGNANTS() {
        initComponents();
         model.addColumn("Id");
        model.addColumn("Nom");
        model.addColumn("Prénom");
         model.addColumn("Adresse");
        model.addColumn("Tél");
        model.addColumn("Fonction");
        model.addColumn("Type");
        t1.setText(""+entier());
        
       try{
//2.Enregistrer le driver JDBC
Class.forName("com.mysql.jdbc.Driver");
}catch(ClassNotFoundException e)
{System.out.println("erreur du chargement du driver"+e);
}
        try{
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
//4creation d'un Statement

Statement st=con.createStatement();

//5.execution d'une requete (ResultSet)

ResultSet Rs=st.executeQuery("Select * from enseignant");
            while(Rs.next()){
                model.addRow(new Object[]{Rs.getString("Id"),Rs.getString("Nom"),Rs.getString("Prénom"),Rs.getString("Adresse"),Rs.getString("Tél"),Rs.getString("Fonction"),Rs.getString("Type")});
            }



st.close();
con.close();
}

catch (SQLException sql){
System.err.println("erreur lors de la connexion"+sql);
 
}
        tbl.setModel(model);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        combo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        t7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nom :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 180, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Id : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 150, 36, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Adresse :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 240, 70, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Prénom :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 210, 80, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("   Télephone : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 270, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Fonction :  ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 300, 80, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Type : ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 330, 60, 20);
        getContentPane().add(t1);
        t1.setBounds(100, 150, 170, 20);
        getContentPane().add(t2);
        t2.setBounds(100, 180, 170, 20);
        getContentPane().add(t3);
        t3.setBounds(100, 210, 170, 20);
        getContentPane().add(t4);
        t4.setBounds(100, 240, 170, 20);
        getContentPane().add(t5);
        t5.setBounds(100, 270, 170, 20);
        getContentPane().add(t6);
        t6.setBounds(100, 300, 170, 20);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/save_f2.png"))); // NOI18N
        jButton1.setText("Enregistrer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 280, 170, 50);

        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Permanent", "Vacataire" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo);
        combo.setBounds(100, 330, 170, 20);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Prenom", "Adresse", "Telephone", "Fonction", "Type"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 160, 452, 90);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/trash.png"))); // NOI18N
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 340, 170, 50);

        b2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/config.png"))); // NOI18N
        b2.setText("Modifier");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(490, 280, 200, 50);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/actua.png"))); // NOI18N
        jButton3.setText("Actualiser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(710, 280, 160, 51);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/query.png"))); // NOI18N
        jButton4.setText("Rechercher");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(490, 340, 200, 50);

        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        getContentPane().add(t7);
        t7.setBounds(700, 350, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gestion de Convocation des Examens");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 10, 710, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/uu.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 0, 110, 60);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/addusers.png"))); // NOI18N
        jLabel10.setText("ENSEIGNANT");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 80, 310, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/F.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 910, 60);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/excel.png"))); // NOI18N
        jButton5.setText("Importation Excel ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(320, 415, 280, 50);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/retour.png"))); // NOI18N
        jButton6.setText("Retour");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 70, 150, 40);

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/decon.png"))); // NOI18N
        jButton7.setText("Deconnexion");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(670, 70, 230, 50);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Copyright MI3-Info juin 2015");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(310, 480, 400, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/F.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 480, 910, 50);

        jLabel13.setText("Le Excel Enseignant que vous importez, il faut que ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(610, 410, 290, 20);

        jLabel12.setText("s'a soit de type CSV, nom EXCEL et il faut mettre");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(610, 430, 280, 14);

        jLabel16.setText("dans votre disque D.");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(610, 440, 230, 20);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/VRAI.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 60, 910, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deplace (int i){
try{
    t1.setText(model.getValueAt(i,0).toString());
       t2.setText(model.getValueAt(i,1).toString());
       t3.setText(model.getValueAt(i,2).toString());
       t4.setText(model.getValueAt(i,3).toString());
       t5.setText(model.getValueAt(i,4).toString());
       t6.setText(model.getValueAt(i,5).toString());
       combo.setSelectedItem(model.getValueAt(i,6).toString());
       
}catch (Exception e){System.err.println(e);

JOptionPane.showMessageDialog(null,"erreur deplacement"+e.getLocalizedMessage());}
}
    
    
    
     private void afficher(){
   
        try{
//2.Enregistrer le driver JDBC
Class.forName("com.mysql.jdbc.Driver");
}catch(ClassNotFoundException e)
{System.out.println("erreur du chargement du driver"+e);
}
        try{
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
//4creation d'un Statement

Statement st=con.createStatement();

//5.execution d'une requete (ResultSet)
 model.setRowCount(0);
ResultSet Rs=st.executeQuery("Select * from enseignant");
            while(Rs.next()){
                model.addRow(new Object[]{Rs.getString("Id"),Rs.getString("Nom"),Rs.getString("Prénom"),Rs.getString("Adresse"),Rs.getString("Tél"),Rs.getString("Fonction"),Rs.getString("Type")});
            }



st.close();
con.close();
}

catch (SQLException sql){
System.err.println("erreur lors de la connexion"+sql);
 
}
        tbl.setModel(model);
    }
    
     
     
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
//2.Enregistrer le driver JDBC
Class.forName("com.mysql.jdbc.Driver");
}catch(ClassNotFoundException e)
{System.out.println("erreur du chargement du driver"+e);
}
try{
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
//4creation d'un Statement

Statement st=con.createStatement();

//5.execution d'une requete (ResultSet)

String query=("INSERT INTO enseignant VALUES"+"('"+t1.getText()+"','"+t2.getText()+"','"+t3.getText()+"','"+t4.getText()+"','"+t5.getText()+"','"+t6.getText()+"','"+combo.getSelectedItem()+"')");

st.executeUpdate(query);
JOptionPane.showMessageDialog(null,"l'enseignant est bien Enregistrer");
       t1.setText(""+entier());
       t2.setText("");
       t3.setText("");
       t4.setText("");
       t5.setText("");
       t6.setText("");
       combo.setSelectedItem(2);
          afficher();
st.close();
con.close();
}

catch (SQLException sql){
System.err.println("erreur lors de la connexion"+sql);

    }                                  
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            //2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException e)
        {System.out.println("erreur du chargement du driver"+e);
        }
        try{
            //3.connextion a la basse

            //String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
            //4creation d'un Statement

            Statement st=con.createStatement();

            //5.execution d'une requete (ResultSet)

            if(JOptionPane.showConfirmDialog(null,"Attention vous etes en train de supprimer un enseignant , Est ce que vous etes sure?"
                ,"Supprimer Secteur",
                JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION)
        if(t1.getText().length() !=0){

            st.executeUpdate("Delete from enseignant WHERE Id="+t1.getText());

            afficher();
        }
        else{JOptionPane.showMessageDialog(null,"Veuiller SVP remplir le champ Numero Secteur!");}
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"erreur de Supprimer\n"+e.getMessage());}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:

        try{
            //2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException e)
        {System.out.println("erreur du chargement du driver"+e);
        }
        try{
            //3.connextion a la basse

            //String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
            //4creation d'un Statement

            Statement st=con.createStatement();

            //5.execution d'une requete (ResultSet)

            if(JOptionPane.showConfirmDialog(null,"confirmer la modification","modification",
                JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
            st.executeUpdate("UPDATE enseignant SET Nom='"+t2.getText()+"',Prénom='"+t3.getText()+"',Adresse='"+t4.getText()+"',Tél='"+t5.getText()+"',Fonction='"+t6.getText()+"',Type='"+combo.getSelectedItem()+"'WHERE Id="+t1.getText());
            afficher();

        }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"erreur de Modifier!!!"+e.getMessage());
            System.err.println(e);}
    }//GEN-LAST:event_b2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        t1.setText(""+entier());
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        combo.setSelectedItem(2);
        afficher();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            //2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException e)
        {System.out.println("erreur du chargement du driver"+e);
        }
        try{
            //3.connextion a la basse

            //String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
            //4creation d'un Statement

            Statement st=con.createStatement();

            model.setRowCount(0);//pour vider la liste des client

            ResultSet Rs=st.executeQuery("select * from enseignant WHERE Nom = '"+t7.getText()+"'");

            while (Rs.next()){
                Object[] enseignant={Rs.getInt(1),Rs.getString(2),Rs.getString(3),Rs.getString(4),Rs.getInt(5),Rs.getString(6),Rs.getString(7)};
                model.addRow(enseignant);
            } if (model.getRowCount()== 0){JOptionPane.showMessageDialog(null,"Il y a aucun Enseignant");

            } else { int i=0;
                deplace(i);
            }
        }catch (Exception e){ System.err.println(e);
            JOptionPane.showMessageDialog(null,"erreur\n"+e.getMessage());
        }

        //5.execution d'une requete (ResultSet)

    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        
         try{
            int i=tbl.getSelectedRow();
            deplace(i);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());}
    }//GEN-LAST:event_tblMouseClicked

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String csvFile = "d:/EXCEL.csv";
	BufferedReader br = null;
	String line = "";
	String cvsSplitBy = ";";
 
	try {
 
		br = new BufferedReader(new FileReader(csvFile));
		while ((line = br.readLine()) != null) {
 
		        
                               // use comma as separator
			String[] enseignants = line.split(cvsSplitBy);
 
           System.out.println("nom " + enseignants[0] 
                                 + " , prenom" + enseignants[1]);
 
	try{
//2.Enregistrer le driver JDBC
Class.forName("com.mysql.jdbc.Driver");
}catch(ClassNotFoundException e)
{System.out.println("erreur du chargement du driver"+e);
}
try{
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
//4creation d'un Statement

Statement st=con.createStatement();

//5.execution d'une requete (ResultSet)

String query=("INSERT INTO enseignant VALUES"+"("+enseignants[0]+",'"+enseignants[1]+"','"+enseignants[2]+"','"+enseignants[3]+"',"+enseignants[4]+",'"+enseignants[5]+"','"+enseignants[6]+"')");
System.out.println(query);
st.executeUpdate(query);

   afficher();    
st.close();
con.close();
}

catch (SQLException sql){
System.err.println("erreur lors de la connexion"+sql);

    }                    	
                
                }
                JOptionPane.showMessageDialog(null,"le fichier excel est bien Enregistrer");
 
	} catch (FileNotFoundException e) {
		e.printStackTrace();
	} catch (IOException e) {
		e.printStackTrace();
	} finally {
		if (br != null) {
			try {
				br.close();
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}
 
	System.out.println("Done");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Menuform AN =new Menuform();
                 AN.setSize(927, 556);
                AN.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         Administrateur A =new Administrateur();
                A.setSize(927, 556);
                A.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ENSEIGNANTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ENSEIGNANTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ENSEIGNANTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ENSEIGNANTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 ENSEIGNANTS AN =new ENSEIGNANTS();
                AN.setSize(927, 556);
                AN.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2;
    private javax.swing.JComboBox combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

public int entier(){
		int nb=1;
		try {
			Class.forName("com.mysql.jdbc.Driver");
			
			String url = "jdbc:mysql://localhost:3306/gestionconvo";
			try {
				Connection con = DriverManager.getConnection(url,"root","");
				Statement st = con.createStatement();
				
				ResultSet rs=st.executeQuery("Select Id from enseignant");
				
				while(rs.next()){
					if(nb==rs.getInt("Id")){
						nb++;
					}
				}
				
				rs.close();
				st.close();
				con.close();
				
				
				
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return nb;
	}



}
