/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_convo;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author joseph chek
 */
public class MATIERE extends javax.swing.JFrame {
DefaultTableModel model=new DefaultTableModel();
    /**
     * Creates new form MATIERE
     */
    public MATIERE() {
       initComponents();
        model.addColumn("Id_mat");
        model.addColumn("Coefficient");
        model.addColumn("lib_mat");
       t1.setText(""+entier());
       
       try{
//2.Enregistrer le driver JDBC
Class.forName("com.mysql.jdbc.Driver");
}catch(ClassNotFoundException e)
{System.out.println("erreur du chargement du driver"+e);
}
        try{
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
//4creation d'un Statement

Statement st=con.createStatement();

//5.execution d'une requete (ResultSet)

ResultSet Rs=st.executeQuery("Select * from matiére");
            while(Rs.next()){
                model.addRow(new Object[]{Rs.getString("Id_mat"),Rs.getString("Coefficient"),Rs.getString("lib_mat")});
            }



st.close();
con.close();
}

catch (SQLException sql){
System.err.println("erreur lors de la connexion"+sql);
 
}
            tbl.setModel(model);
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        t7 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Nom de la matiere: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 210, 180, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Id_matiere :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 170, 170, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Coefficient :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 250, 120, 20);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(200, 160, 210, 30);
        getContentPane().add(t2);
        t2.setBounds(200, 200, 210, 30);
        getContentPane().add(t3);
        t3.setBounds(200, 240, 210, 30);

        b1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/save_f2.png"))); // NOI18N
        b1.setText("Enregistrer");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(250, 280, 180, 50);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id_matiere", "Coefficient", "Nom de la matiere"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(440, 160, 430, 110);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/trash.png"))); // NOI18N
        jButton2.setText("Supprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 340, 180, 50);

        b2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/config.png"))); // NOI18N
        b2.setText("Modifier");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(440, 280, 180, 50);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/actua.png"))); // NOI18N
        jButton3.setText("Actualiser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(640, 280, 160, 50);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/query.png"))); // NOI18N
        jButton4.setText("Rechercher");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(440, 340, 180, 50);
        getContentPane().add(t7);
        t7.setBounds(630, 350, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/mat.png"))); // NOI18N
        jLabel2.setText("Matiére");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 80, 240, 70);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gestion de Convocation des Examens");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 10, 710, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/uu.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 0, 110, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/F.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 910, 70);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/decon.png"))); // NOI18N
        jButton1.setText("Deconnexion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(680, 70, 220, 50);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/retour.png"))); // NOI18N
        jButton5.setText("Retour");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 80, 150, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Copyright MI3-Info juin 2015");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(310, 480, 400, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/F.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 480, 910, 50);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/excel.png"))); // NOI18N
        jButton6.setText("Importation Excel ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 410, 280, 50);

        jLabel13.setText("Le Excel Matiére que vous importez, il faut que ");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(300, 410, 290, 20);

        jLabel12.setText("s'a soit de type CSV, nom EXCEL et il faut mettre");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 430, 280, 14);

        jLabel16.setText("dans votre disque D.");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(300, 446, 230, 14);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/VRAI.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 60, 910, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void deplace (int i){
try{
    t1.setText(model.getValueAt(i,0).toString());
       t2.setText(model.getValueAt(i,1).toString());
       t3.setText(model.getValueAt(i,2).toString());
       
       
}catch (Exception e){System.err.println(e);

JOptionPane.showMessageDialog(null,"erreur deplacement"+e.getLocalizedMessage());}
}  
  
  
  
  private void afficher(){
   
        try{
//2.Enregistrer le driver JDBC
Class.forName("com.mysql.jdbc.Driver");
}catch(ClassNotFoundException e)
{System.out.println("erreur du chargement du driver"+e);
}
        try{
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
//4creation d'un Statement

Statement st=con.createStatement();

//5.execution d'une requete (ResultSet)
 model.setRowCount(0);
ResultSet Rs=st.executeQuery("Select * from matiére");
            while(Rs.next()){
                model.addRow(new Object[]{Rs.getString("Id_mat"),Rs.getString("Coefficient"),Rs.getString("lib_mat")});
            }



st.close();
con.close();
}

catch (SQLException sql){
System.err.println("erreur lors de la connexion"+sql);
 
}
        tbl.setModel(model);
    }
    
    
    
    
    
    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_t1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:

        try{
            //2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException e)
        {System.out.println("erreur du chargement du driver"+e);
        }
        try{
            //3.connextion a la basse

            //String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
            //4creation d'un Statement

            Statement st=con.createStatement();

            //5.execution d'une requete (ResultSet)

            String query=("INSERT INTO matiére VALUES"+"('"+t1.getText()+"','"+t3.getText()+"','"+t2.getText()+"')");

            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"la matiere est bien Enregistrer");
            t1.setText(""+entier());
            t2.setText("");
            t3.setText("");
                 afficher();
            st.close();
            con.close();
        }

        catch (SQLException sql){
            System.err.println("erreur lors de la connexion"+sql);

        }

    }//GEN-LAST:event_b1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            //2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException e)
        {System.out.println("erreur du chargement du driver"+e);} 
        try{
            //3.connextion a la basse

            //String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
            //4creation d'un Statement

            Statement st=con.createStatement();

            //5.execution d'une requete (ResultSet)

            if(JOptionPane.showConfirmDialog(null,"Attention vous etes en train de supprimer une matiere , Est ce que vous etes sure?"
                ,"Supprimer Matiere",
                JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION)
        if(t1.getText().length() !=0){

            st.executeUpdate("Delete from matiére WHERE Id_mat="+t1.getText());

            afficher();
        }
        else{JOptionPane.showMessageDialog(null,"Veuiller SVP remplir le champ Numero Secteur!");}
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"erreur de Supprimer\n"+e.getMessage());}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:

        try{
            //2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException e)
        {System.out.println("erreur du chargement du driver"+e);
        }
        try{
            //3.connextion a la basse

            //String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
            //4creation d'un Statement

            Statement st=con.createStatement();

            //5.execution d'une requete (ResultSet)

            if(JOptionPane.showConfirmDialog(null,"confirmer la modification","modification",
                JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
            st.executeUpdate("UPDATE matiére SET lib_mat='"+t2.getText()+"',Coefficient='"+t3.getText()+"'WHERE Id_mat="+t1.getText());
            afficher();

        }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"erreur de Modifier!!!"+e.getMessage());
            System.err.println(e);}
    }//GEN-LAST:event_b2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        t1.setText(""+entier());
        t2.setText("");
        t3.setText("");
        
        afficher();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            //2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        }catch(ClassNotFoundException e)
        {System.out.println("erreur du chargement du driver"+e);
        }
        try{
            //3.connextion a la basse

            //String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
            //4creation d'un Statement

            Statement st=con.createStatement();

            model.setRowCount(0);//pour vider la liste des client

            ResultSet Rs=st.executeQuery("select * from matiére WHERE lib_mat = '"+t7.getText()+"'");

            while (Rs.next()){
                Object[] matiére={Rs.getInt(1),Rs.getInt(2),Rs.getString(3)};
                model.addRow(matiére);
            } if (model.getRowCount()== 0){JOptionPane.showMessageDialog(null,"Il y a aucun Matiere de ce nom");

            } else { int i=0;
                deplace(i);
            }
        }catch (Exception e){ System.err.println(e);
            JOptionPane.showMessageDialog(null,"erreur\n"+e.getMessage());
        }

        //5.execution d'une requete (ResultSet)
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        
        try{
            int i=tbl.getSelectedRow();
            deplace(i);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());}
    }//GEN-LAST:event_tblMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Administrateur A =new Administrateur();
                A.setSize(927, 556);
                A.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Menuform AN =new Menuform();
                 AN.setSize(927, 556);
                AN.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String csvFile = "d:/matiere.csv";
        BufferedReader br = null;
        String line = "";
        String cvsSplitBy = ";";

        try {

            br = new BufferedReader(new FileReader(csvFile));
            while ((line = br.readLine()) != null) {

                // use comma as separator
                String[] matiere = line.split(cvsSplitBy);

                System.out.println("nom " + matiere[0]
                    + " , Coefficient" + matiere[1]);

                try{
                    //2.Enregistrer le driver JDBC
                    Class.forName("com.mysql.jdbc.Driver");
                }catch(ClassNotFoundException e)
                {System.out.println("erreur du chargement du driver"+e);
                }
                try{
                    //3.connextion a la basse

                    //String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo","root","");
                    //4creation d'un Statement

                    Statement st=con.createStatement();

                    //5.execution d'une requete (ResultSet)

                    String query=("INSERT INTO matiére VALUES"+"("+matiere[0]+","+matiere[1]+",'"+matiere[2]+"')");
                    System.out.println(query);
                    st.executeUpdate(query);

                    afficher();
                    st.close();
                    con.close();
                }

                catch (SQLException sql){
                    System.err.println("erreur lors de la connexion"+sql);

                }

            }
            JOptionPane.showMessageDialog(null,"le fichier excel est bien Enregistrer");

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (br != null) {
                try {
                    br.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }

        System.out.println("Done");

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MATIERE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MATIERE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MATIERE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MATIERE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MATIERE A =new MATIERE();
                A.setSize(927, 556);
                A.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t7;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

public int entier(){
		int nb=1;
		try {
			Class.forName("com.mysql.jdbc.Driver");
			
			String url = "jdbc:mysql://localhost:3306/gestionconvo";
			try {
				Connection con = DriverManager.getConnection(url,"root","");
				Statement st = con.createStatement();
				
				ResultSet rs=st.executeQuery("Select Id_mat from matiére");
				
				while(rs.next()){
					if(nb==rs.getInt("Id_mat")){
						nb++;
					}
				}
				
				rs.close();
				st.close();
				con.close();
				
				
				
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
			
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return nb;
	}

}










