/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_convo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.print.*;
import java.text.*;
import javax.swing.JTable;

/**
 *
 * @author joseph chek
 */
public class salle extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form ense
     */
    public salle() {
        initComponents();
        model.addColumn("Id_sal");
        model.addColumn("Nom_sal");
        model.addColumn("capacité");
        t1.setText("" + entier());
        try {
//2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("erreur du chargement du driver" + e);
        }
        try {
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo", "root", "");
//4creation d'un Statement

            Statement st = con.createStatement();

//5.execution d'une requete (ResultSet)
            ResultSet Rs = st.executeQuery("Select * from salle");
            while (Rs.next()) {
                model.addRow(new Object[]{Rs.getString("Id_sal"), Rs.getString("Nom_sal"), Rs.getString("capacité")});
            }

            st.close();
            con.close();
        } catch (SQLException sql) {
            System.err.println("erreur lors de la connexion" + sql);

        }
        tbl.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Capacite de salle :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 280, 130, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Id_salle :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 220, 120, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nom de salle :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 250, 130, 20);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(160, 220, 140, 20);
        getContentPane().add(t2);
        t2.setBounds(160, 250, 140, 20);
        getContentPane().add(t3);
        t3.setBounds(160, 280, 140, 20);

        b1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/save_f2.png"))); // NOI18N
        b1.setText("Enregistrer");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(250, 320, 200, 50);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(370, 200, 410, 90);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/trash.png"))); // NOI18N
        jButton1.setText("Supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 380, 200, 50);

        b2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/config.png"))); // NOI18N
        b2.setText("Modifier");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(460, 320, 200, 50);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/actua.png"))); // NOI18N
        jButton2.setText("Actualiser");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(680, 320, 200, 51);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/query.png"))); // NOI18N
        jButton3.setText("Rechercher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(460, 380, 210, 50);
        getContentPane().add(t4);
        t4.setBounds(690, 390, 170, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Gestion de Convocation des Examens");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(170, 10, 710, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/uu.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 0, 110, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/sall.png"))); // NOI18N
        jLabel2.setText("Salle");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 70, 290, 90);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/F.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 910, 60);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/retour.png"))); // NOI18N
        jButton5.setText("Retour");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 70, 150, 43);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/decon.png"))); // NOI18N
        jButton4.setText("Deconnexion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(680, 70, 220, 49);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Copyright MI3-Info juin 2015");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(310, 480, 400, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/F.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 480, 910, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestion_convo/VRAI.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 60, 910, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void deplace(int i) {
        try {
            t1.setText(model.getValueAt(i, 0).toString());
            t2.setText(model.getValueAt(i, 1).toString());
            t3.setText(model.getValueAt(i, 2).toString());

        } catch (Exception e) {
            System.err.println(e);

            JOptionPane.showMessageDialog(null, "erreur deplacement" + e.getLocalizedMessage());
        }
    }
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:

        try {
//2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("erreur du chargement du driver" + e);
        }
        try {
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo", "root", "");
//4creation d'un Statement

            Statement st = con.createStatement();

//5.execution d'une requete (ResultSet)
            String query = ("INSERT INTO salle VALUES" + "('" + t1.getText() + "','" + t2.getText() + "','" + t3.getText() + "')");

            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "la salle est bien Enregistrer");
            t1.setText("" + entier());
            t2.setText("");
            t3.setText("");
            afficher();

            st.close();
            con.close();
        } catch (SQLException sql) {
            System.err.println("erreur lors de la connexio n" + sql);
        }

    }//GEN-LAST:event_b1ActionPerformed

    private void afficher() {

        try {
//2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("erreur du chargement du driver" + e);
        }
        try {
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo", "root", "");
//4creation d'un Statement

            Statement st = con.createStatement();

//5.execution d'une requete (ResultSet)
            model.setRowCount(0);
            ResultSet Rs = st.executeQuery("Select * from salle");
            while (Rs.next()) {
                model.addRow(new Object[]{Rs.getString("Id_sal"), Rs.getString("Nom_sal"), Rs.getString("capacité")});
            }

            st.close();
            con.close();
        } catch (SQLException sql) {
            System.err.println("erreur lors de la connexion" + sql);

        }
        tbl.setModel(model);
    }


    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_t1ActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        try {
            int i = tbl.getSelectedRow();
            deplace(i);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erreur de deplacement" + e.getLocalizedMessage());
        }

    }//GEN-LAST:event_tblMouseClicked

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:

        try {
//2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("erreur du chargement du driver" + e);
        }
        try {
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo", "root", "");
//4creation d'un Statement

            Statement st = con.createStatement();

//5.execution d'une requete (ResultSet)
            if (JOptionPane.showConfirmDialog(null, "confirmer la modification", "modification",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                st.executeUpdate("UPDATE salle SET Nom_sal='" + t2.getText() + "',capacité='" + t3.getText() + "'WHERE Id_sal=" + t1.getText());
                afficher();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erreur de Modifier!!!" + e.getMessage());
            System.err.println(e);
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
//2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("erreur du chargement du driver" + e);
        }
        try {
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo", "root", "");
//4creation d'un Statement

            Statement st = con.createStatement();

//5.execution d'une requete (ResultSet)
            if (JOptionPane.showConfirmDialog(null, "Attention vous etes en train de supprimer une salle , Est ce que vous etes sure?", "Supprimer Secteur",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                if (t1.getText().length() != 0) {

                    st.executeUpdate("Delete from salle WHERE Id_sal=" + t1.getText());

                    afficher();
                } else {
                    JOptionPane.showMessageDialog(null, "Veuiller SVP remplir le champ Numero Secteur!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erreur de Supprimer\n" + e.getMessage());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        t1.setText("" + entier());
        t2.setText("");
        t3.setText("");

        afficher();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
//2.Enregistrer le driver JDBC
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            System.out.println("erreur du chargement du driver" + e);
        }
        try {
//3.connextion a la basse

//String url=("jdbc:mysql://localhost:3306/gestion_emprunt2","root","");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gestionconvo", "root", "");
//4creation d'un Statement

            Statement st = con.createStatement();

            model.setRowCount(0);//pour vider la liste des client

            ResultSet Rs = st.executeQuery("select * from salle WHERE Nom_sal= '" + t4.getText() + "'");

            while (Rs.next()) {
                Object[] salle = {Rs.getInt(1), Rs.getString(2), Rs.getInt(3)};
                model.addRow(salle);
            }
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Il y a aucun Salle");

            } else {
                int i = 0;
                deplace(i);
            }
        } catch (Exception e) {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "erreur\n" + e.getMessage());
        }

//5.execution d'une requete (ResultSet)  

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Menuform AN =new Menuform();
                 AN.setSize(927, 556);
                AN.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         Administrateur A =new Administrateur();
                A.setSize(927, 556);
                A.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(salle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                salle p = new salle();
                p.setSize(927, 556);
                p.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

    public int entier() {
        int nb = 1;
        try {
            Class.forName("com.mysql.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/gestionconvo";
            try {
                Connection con = DriverManager.getConnection(url, "root", "");
                Statement st = con.createStatement();

                ResultSet rs = st.executeQuery("Select Id_sal from salle");

                while (rs.next()) {
                    if (nb == rs.getInt("Id_sal")) {
                        nb++;
                    }
                }

                rs.close();
                st.close();
                con.close();

            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

        } catch (ClassNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        return nb;
    }

}
